export const ROUTES = {
  home: '/',
  pricing: '/pricing',
  buyPlan: '/buy-plan',
  contact: '/contact',
  contactSales: '/contact/sales',
  contactSupport: '/contact/support',
  resources: '/resources',
  auth: {
    root: '/auth',
    login: '/auth/login',
    signup: '/auth/signup',
    forgotPassword: '/auth/forgot-password',
  },
  dashboard: {
    root: '/dashboard',
    user: '/dashboard/user',
    users: '/dashboard/users',
    roles: '/dashboard/roles',
    saleRegister: '/dashboard/sale-register',
    gstr1: '/dashboard/gstr-1',
    gstr1a: '/dashboard/gstr-1a',
    purchaseRegister: '/dashboard/purchase-register',
    ims: '/dashboard/ims',
    gstr2a: '/dashboard/gstr-2a',
    gstr2b: '/dashboard/gstr-2b',
    itc03: '/dashboard/itc-03',
    itc04: '/dashboard/itc-04',
    eInvoice: '/dashboard/e-invoice',
    eWayBill: '/dashboard/e-way-bill',
    gstr3b: '/dashboard/gstr-3b',
    gstr9: '/dashboard/gstr-9',
    gstr9c: '/dashboard/gstr-9c',
    gstLedgers: '/dashboard/gst-ledgers',
    vendorLedger: '/dashboard/vendor-ledger',
    challan: '/dashboard/challan',
  },
  notFound: '*',
} as const;
